assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        angular:
            inputs:
                - '%kernel.root_dir%/../node_modules/angular/angular.min.js'
        vendor:
            inputs:
                - '%kernel.root_dir%/Resources/public/css/vendor.css'
