homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

post_index:
    path:     /post
    defaults: { _controller: "AppBundle:Post:index" }
    methods:  GET

post_show:
    path:     /post/{id}/show
    defaults: { _controller: "AppBundle:Post:show" }
    methods:  GET

post_new:
    path:     /post/new
    defaults: { _controller: "AppBundle:Post:new" }
    methods:  [GET, POST]

post_edit:
    path:     /post/{id}/edit
    defaults: { _controller: "AppBundle:Post:edit" }
    methods:  [GET, POST]

post_delete:
    path:     /post/{id}/delete
    defaults: { _controller: "AppBundle:Post:delete" }
    methods:  DELETE
