# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    guzzle:
        public: false
        class: GuzzleHttp\Client
    short_url:
        class: AppBundle\Util\ShortUrl
        arguments: ['@guzzle']
